# Generated by Django 3.2.5 on 2021-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('client_id', models.CharField(default='htm-cl-', max_length=15, primary_key=True, serialize=False, verbose_name='client_id')),
                ('client_name', models.CharField(default='Name', max_length=50, verbose_name='client_name')),
                ('client_mail', models.CharField(default='Mail', max_length=100, verbose_name='client_mail')),
                ('client_request', models.CharField(default='Service', max_length=50, verbose_name='client_request')),
                ('client_quote', models.CharField(default='$ 0', max_length=5, verbose_name='client_quote')),
                ('org_name', models.CharField(default='Company', max_length=100, verbose_name='organization')),
                ('org_web', models.CharField(default='Company', max_length=100, verbose_name='website')),
                ('request_time', models.CharField(default='', max_length=100, verbose_name='request_time')),
            ],
        ),
    ]
