# Generated by Django 3.2.6 on 2021-09-16 13:13

import django.contrib.postgres.fields
from django.db import migrations, models
import maillytics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDetail',
            fields=[
                ('cid', models.CharField(default='MPT', max_length=11, primary_key=True, serialize=False, verbose_name='Campaign ID')),
                ('cname', models.CharField(default='campaign', max_length=75, verbose_name='Campaign Name')),
                ('ca', models.CharField(default='', max_length=200, verbose_name='campaign_action')),
                ('ba', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=maillytics.models.get_ba_link_defaults, size=6, verbose_name='brand_action')),
                ('htma', models.CharField(default='https://healtentmedia.com', max_length=25, verbose_name='htm_action')),
            ],
        ),
        migrations.CreateModel(
            name='MailAnalytic',
            fields=[
                ('cid', models.CharField(default='MPT', max_length=11, verbose_name='Campaign ID')),
                ('tid', models.CharField(default='', max_length=4, primary_key=True, serialize=False, verbose_name='Target ID')),
                ('open', models.BooleanField(default=False, max_length=5, verbose_name='open_action')),
                ('clicks', models.IntegerField(default=0, verbose_name='clicks')),
                ('country', models.CharField(default='', max_length=100, verbose_name='Country')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('ca', models.IntegerField(default=0, verbose_name='campaign_action')),
                ('ba', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=maillytics.models.get_ba_defaults, size=6, verbose_name='brand_action')),
                ('htma', models.IntegerField(default=0, verbose_name='htm_action')),
            ],
        ),
    ]
